apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "typesense-operator.fullname" . }}-metrics-reader
  namespace: {{ include "typesense-operator.namespace" . | quote }}
  labels:
  {{- include "typesense-operator.labels" . | nindent 4 }}
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
