apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "typesense-operator.fullname" . }}-controller-manager
  namespace: {{ include "typesense-operator.namespace" . | quote }}
  labels:
  {{- include "typesense-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}
