apiVersion: ts.opentelekomcloud.com/v1alpha1
kind: TypesenseCluster
metadata:
  labels:
    app.kubernetes.io/name: typesense-operator
    app.kubernetes.io/managed-by: kustomize
  name: c-otc-1
spec:
  image: typesense/typesense:27.1
  replicas: 3
  storage:
    size: 10Mi
    storageClassName: csi-disk
  ingress:
    referer: ts.sydpaa.de
    host: ts-test.sydpaa.de
    ingressClassName: cce
    clusterIssuer: opentelekomcloud-letsencrypt
---
apiVersion: ts.opentelekomcloud.com/v1alpha1
kind: TypesenseCluster
metadata:
  labels:
    app.kubernetes.io/name: typesense-operator
    app.kubernetes.io/managed-by: kustomize
  name: c-otc-2
spec:
  image: typesense/typesense:26.0
  replicas: 1
  storage:
    storageClassName: csi-disk
---
apiVersion: ts.opentelekomcloud.com/v1alpha1
kind: TypesenseCluster
metadata:
  labels:
    app.kubernetes.io/name: typesense-operator
    app.kubernetes.io/managed-by: kustomize
  name: c-otc-3
spec:
  image: typesense/typesense:26.0
  replicas: 3
  storage:
    storageClassName: csi-obs